name: 'write-secret-to-file'
description: 'Write encoded secret to file'
inputs:
  path:  
    description: 'file path to write'
    required: true
    default: './'
  content:
    description: 'encoded secret'
    required: true
    default: '*****'
# outputs:
#   time: # output will be available to future steps
#     description: 'The current time after waiting'
runs:
  using: 'node16'
  main: 'dist/index.js'
